rtl_433:
  load: RTL_433
  module: fixgw.plugins.rtl_433
  simulate: true
  sensors:
    - sensor_id: 12345   # TPMS ID for front wheel
      decoder: 234  # The decoder needed to capture this data
      mappings:
        TIRE_PRESSURE1:
          source: "pressure_kPa"
          scale: 6.89476  # Convert kPa to PSI
          round: 1
          type: "float"
        TIRE_TEMP1:
          source: "temperature_C"
          offset: -40
          round: 0
          type: "float"
        TIRE_BATOK1:
          source: "battery_V"
          threshold: 2.0  # Battery OK if voltage > 2.0 (1 = OK, 0 = Low)
          type: "bool"


