rtl_433:
  load: RTL_433
  module: fixgw.plugins.rtl_433
  frequency: 433920000
  rtl_device: 0
  #simulate: true
  sensors:
    - sensor_id: "007847C1A7"   # TPMS ID for front wheel
      decoder: 275  # The decoder needed to capture this data
      mappings:
        TIREP1:
          source: "pressure_kPa"
          #scale: 6.89476  # Convert kPa to PSI
          round: 1
          type: "float"
        TIRET1:
          source: "temperature_C"
          #offset: -40
          round: 0
          type: "float"
        TIREB1:
          source: "battery_ok"
          #threshold: 2.0  # Battery OK if voltage > 2.0 (1 = OK, 0 = Low)
          type: "bool"
    - sensor_id: "0078491766"   # TPMS ID for front wheel
      decoder: 275  # The decoder needed to capture this data
      mappings:
        TIREP2:
          source: "pressure_kPa"
          round: 1
          type: "float"
        TIRET2:
          source: "temperature_C"
          round: 0
          type: "float"
        TIREB2:
          source: "battery_ok"
          type: "bool"
    - sensor_id: "0078473B61"   # TPMS ID for front wheel
      decoder: 275  # The decoder needed to capture this data
      mappings:
        TIREP3:
          source: "pressure_kPa"
          round: 1
          type: "float"
        TIRET3:
          source: "temperature_C"
          round: 0
          type: "float"
        TIREB3:
          source: "battery_ok"
          type: "bool"

