# Avoid editing this file
# Future updates may include changes to this file but once you edit
# this file it will no longer be auto-updated and you will not
# benefit from the improvements without manual intervention

# If you want to edit min/max/initial/tol/etc
# Do that in the file custom.ini

items:
# Used by mavlink plugin:
- key: TRIMP
  description: Pitch Trim
  type: float
  min: -100
  max: 100
  initial: 0
- key: TRIMR
  description: Roll Trim
  type: float
  min: -100
  max: 100
  initial: 0
- key: TRIMY
  description: Yaw Trim
  type: float
  min: -100
  max: 100
  initial: 0

